<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_psw</name>
   <tag></tag>
   <elementGuidId>f885afca-a93f-44f8-b141-50b248e0a280</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='psw']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;psw&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4426fb96-c011-4974-ab88-f5ca971f82a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0bb08108-4d46-47a2-9e2f-2059aa4d481b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Password</value>
      <webElementGuid>d9137697-7866-4569-a8dc-104d050a528b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>psw</value>
      <webElementGuid>e9181ed8-00d3-4638-ae8c-09ee8c442f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HTML1&quot;)/div[@class=&quot;widget-content&quot;]/form[1]/div[@class=&quot;container&quot;]/input[2]</value>
      <webElementGuid>e07b978d-121d-4cba-8ba1-7da2a9cd7de3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='psw']</value>
      <webElementGuid>0a15505a-3d48-4996-8a4f-9bdf3d2fd8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HTML1']/div/form/div/input[2]</value>
      <webElementGuid>8fc0ef93-ff97-4af1-b755-b3fe752b3b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>ae479f45-2a57-422b-b350-35a4ddb10260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Enter Password' and @name = 'psw']</value>
      <webElementGuid>76e9e8dd-030d-47cf-b0d0-8403fce8d1ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
