<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sortable</name>
   <tag></tag>
   <elementGuidId>b030bc73-e26d-4a4b-8c5b-8cb7ef419a28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.link_span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-2806']/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>56350ae9-83a6-4e77-b3cd-f4b16380c8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link_span</value>
      <webElementGuid>40c6dabc-df78-4243-9e86-8d889d02acfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sortable</value>
      <webElementGuid>f5881cfd-0b5b-4224-9ce2-8e4ac2ff9371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-2806&quot;)/a[1]/span[@class=&quot;link_span&quot;]</value>
      <webElementGuid>b1baa9a6-afbb-401e-af48-a1aa4dc70033</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-2806']/a/span[2]</value>
      <webElementGuid>002caf22-82e3-477d-a171-a4884ddd7042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interaction'])[1]/following::span[2]</value>
      <webElementGuid>3bed6a48-9fe2-46ff-b211-0ff7cb2832e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frames And Windows'])[4]/following::span[3]</value>
      <webElementGuid>d3ef173f-faf1-44ed-8a6f-684ef64b83fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag And Drop'])[3]/preceding::span[2]</value>
      <webElementGuid>5d11b823-5785-4fcf-8067-c8f15c1c9fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Elements'])[3]/preceding::span[4]</value>
      <webElementGuid>df772439-6c3e-4bb0-ac32-2cdecfb234bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sortable']/parent::*</value>
      <webElementGuid>d54ccc3a-258a-46b2-a354-55ec8420c4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span[2]</value>
      <webElementGuid>398750db-3886-4270-a4c8-38121b849bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sortable' or . = 'Sortable')]</value>
      <webElementGuid>289093fe-9176-46bd-ac15-b9c35bc4cc6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
