<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_Share_playerId__28236204--20_html5_api</name>
   <tag></tag>
   <elementGuidId>1c517321-b8b1-4e85-89e5-60ded7ef41fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//video[@id='playerId__28236204--20_html5_api']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#playerId__28236204--20_html5_api</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>4478c854-13bf-4be0-b5fe-5abc34bfa604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vjs-tech</value>
      <webElementGuid>3ae49821-461e-4332-8e44-a46f6852eeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>playerId__28236204--20_html5_api</value>
      <webElementGuid>898061c1-3f17-4048-b356-5be21458f99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>24e29a6b-7f6b-4d33-ad5b-c94411e5108d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controlslist</name>
      <type>Main</type>
      <value>nodownload</value>
      <webElementGuid>ca0df6c3-5cba-4c69-adfb-7837af3c96b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5340cfde-7979-4899-b87f-689d7dd96fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://spaceinternational.udemy.com/86e13472-e621-4e27-b28d-92f26bb28603</value>
      <webElementGuid>b42b40a6-9f91-4065-a811-6a3982e81591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;playerId__28236204--20_html5_api&quot;)</value>
      <webElementGuid>4edf816b-6fb6-41a0-b0af-f963ea2733b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@id='playerId__28236204--20_html5_api']</value>
      <webElementGuid>3963d94d-a44e-41de-b5be-19abecf1693e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='playerId__28236204--20']/video</value>
      <webElementGuid>bb1d3119-436b-4344-9d0e-b07fcdc1dd8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>26e3f4c4-014b-480f-b0c6-a645c74a2b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'playerId__28236204--20_html5_api' and @src = 'blob:https://spaceinternational.udemy.com/86e13472-e621-4e27-b28d-92f26bb28603']</value>
      <webElementGuid>a732899c-9ffc-4775-9db3-dcfddfd099d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
